name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: bashkim-cms-production-ecr
  APP_NAME: bashkim-cms-production-strapi

jobs:
  deploy:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: "git: checkout"
        uses: actions/checkout@v3

      - name: "aws: credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "ecr: login"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "docker: build"
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"
          docker build --platform linux/amd64 -t $IMAGE_URI .

      - name: "ecr: push"
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"
          docker push $IMAGE_URI

      # - name: "apprunner: deploy"
      #   run: |
      #     aws apprunner update-service \
      #       --service-name "${{ env.APP_NAME }}" \
      #       --source-configuration ImageRepository="{ImageIdentifier=$IMAGE_URI,ImageRepositoryType=ECR}"
